version: "3.9"

#  docker exec -it budgettracker-mariadb mariadb -u root --password=root


services:
  mariadb:
    image: mariadb:latest
    container_name: budgettracker-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: budgettracker
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build: .
    container_name: budgettracker-api
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/budgettracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"

volumes:
  mariadb_data:
