spring.application.name=BudgetTrackerAPI

# MariaDB Configuration
# For docker-compose (service name is "mariadb")
spring.datasource.url=jdbc:mariadb://mariadb:3306/budgettracker
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#spring.jpa.hibernate.ddl-auto=none

#validates entities on every run
spring.jpa.hibernate.ddl-auto=validate
#update
spring.jpa.show-sql=true

spring.flyway.baseline-on-migrate=false
spring.flyway.enabled=true

spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

